services:
  bot-uploader:
    build: .
    container_name: telegram-uploader-bot 
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${HOST_UPLOAD_DIR:-/mnt/hdd/telegram-uploads}:/mnt/hdd/telegram-uploads