services:
  bot-uploader:
    build: .
    image: nadex-cloud-bot:latest
    container_name: Nadex
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${HOST_UPLOAD_DIR:-/mnt/hdd/telegram-uploads}:/mnt/hdd/telegram-uploads
    ports:
      - "3030:3000"
    x-casaos:
      port_map: "3030"
      index: "/"
      title:
        custom: Nadex Monitoring
      icon: "https://cdn3.iconfinder.com/data/icons/popular-services-brands-vol-2/512/telegram-512.png"

  mongodb:
    image: mongo:4.4.18
    container_name: Nadex-DB
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main_app: bot-uploader